### PR TITLE
Allow non-primitive default values

### PR DESCRIPTION
**Pull request by yborovikov**
This should fix erroneous highlighting of non-primitive (e.g. array) default values like:

``` Java
    array<string> someStrings = [];
    map<int> someNumbers = { "one" : 1, "two" : 2 };
```

@AbigailBuccaneer - thanks for writing this handy plugin!

### CODE REVIEW

**Comment by AbigailBuccaneer** [comment]
Thanks for your contributions!

(As a side note, you making this pull request caused me to make the pull request github/linguist#2822. You've indirectly improved GitHub!)

**Comment by yborovikov** [comment]
:) Thank you!
Please let me know if I can help with packaging and publishing it in [JetBrains Plugin Repository](https://plugins.jetbrains.com/plugin/7971).

**Comment by AbigailBuccaneer** [comment]
Oh yes, I forgot that step! I'll do it now.

**Comment by AbigailBuccaneer** [comment]
[And it's out!](https://plugins.jetbrains.com/update/index?pr=&updateId=23656)

**Comment by yborovikov** [comment]
Thank you!

**Pull request merged**
